// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpEnUNqgP-P-QwvAZLd238HJzX7_25fhE',
    appId: '1:878293117994:web:f7fea565b630dfb2b92753',
    messagingSenderId: '878293117994',
    projectId: 'tssm-99dd9',
    authDomain: 'tssm-99dd9.firebaseapp.com',
    storageBucket: 'tssm-99dd9.appspot.com',
    measurementId: 'G-4RZZH6L8CM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7gHP0brBXbK3iOUW-J6B-aHNpqOGBrRM',
    appId: '1:878293117994:android:82b9c5cbf582bbd5b92753',
    messagingSenderId: '878293117994',
    projectId: 'tssm-99dd9',
    storageBucket: 'tssm-99dd9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQLRwDc6DeJEHllQYx4XR2j2ASCHMdDb8',
    appId: '1:878293117994:ios:d98f0f5be877d052b92753',
    messagingSenderId: '878293117994',
    projectId: 'tssm-99dd9',
    storageBucket: 'tssm-99dd9.appspot.com',
    iosBundleId: 'com.example.demoTssmAdmission',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQLRwDc6DeJEHllQYx4XR2j2ASCHMdDb8',
    appId: '1:878293117994:ios:3d6868375c00ccbcb92753',
    messagingSenderId: '878293117994',
    projectId: 'tssm-99dd9',
    storageBucket: 'tssm-99dd9.appspot.com',
    iosBundleId: 'com.example.demoTssmAdmission.RunnerTests',
  );
}
